### ISSUE TITLE
How to handle the toml-rb gem and TOML files in general

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppet_operational_dashboards#95]
## Use Case
currently this module installs the toml-rb gem, but the user can not decide

- if he or she wants the module to do this (manage toml_rb_gem switch)
- the version
- needs a proxy or an other source for the gem

## Describe the Solution You Would Like
One option would be to patch this module and the influxdb module it uses to do this
An other option would be to use to_toml() function from stdlib, and get rid of the dependency: https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/REFERENCE.md#to_toml  (I would prefer this)

## Describe Alternatives You've Considered
none

## Additional Context
none

**Comment by m0dular** [comment]
Unfortunately stdlib doesn't have a `from_toml` function equivalent to toml-rb's `load` function, which we need for reading the config files from disk and comparing to the desired state.  I know installing gems isn't the best option and we'd like to avoid it when possible, but I don't see a way around it currently.

The version can be specified in [influxdb::profile::toml](https://github.com/puppetlabs/influxdb/blob/main/manifests/profile/toml.pp#L4-L5), but like you said it's not great when you have a proxy or airgap.

I guess if you are ok with not using SSL for InfluxDB and using Bolt, you could use the [provision dashboard plan](https://github.com/puppetlabs/puppet_operational_dashboards/blob/main/plans/provision_dashboard.pp).  That sort of gets around the gem issue because you can install it locally with Bolt, so it doesn't have to be installed on the target machine.

```
/opt/puppetlabs/bolt/bin/gem install --user-install toml-rb
```
I'll leave this open for now so people can leave comments and suggestions, but I think `toml-rb` will probably remain a requirement.

**Comment by SimonHoenscheid** [comment]
the missing from_toml (stdlib has load$DATAFORMAT) and parse$DATAFORMAT for this case. I will have a look at these and figure out if these are a good guideline for a TOML implementation.

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/puppet-telegraf/pull/207 for telegraf we're switching to the stdlib implementation to get rid of toml.

**Comment by zoojar** [comment]
#219  Added option to specify yaml instead of toml, removing the dependency on the toml gem completely

**Comment by SimonHoenscheid** [comment]
@zoojar thanks for the PR!
